AUTHORS
=> #1 Added name to Author file

AUTHORS, JakeyD11/index.html, JakeyD11/style.css, README.md
I didnt branch off for individual tasks my bad i wont do it again i promise
=> Multiple Tasks

jennifer-carey/index.html
Just set up a html template ready for extra code
=> Added index.html file

JoeFoster-cn/README.md
Created a folder with my GitHub username containing a README.md file
=> #3 Created username folder containing README file

jennifer-carey/index.html
PLEASE CHECK THE MOST RECENT - #4 trying to push HTML again
=> #4 HTML content added

JoeFoster-cn/index.html
Created index.html with table and iframe
=> #4 Created HTML file

README.md
Added github profile and portfolio links
=> 2 Add a link to your github profile & github pages url to the README.md file

sarahnwright/README.md
=> #3 sarahnwright

ap42m/index.html
Added the idex.html file with a table of songs and embeded video
=> #4 index.html / table / iframe

nisharai26/switchExample.js
=> 7 In your user area write a small nodejs program

JoeFoster-cn/index.html, JoeFoster-cn/node.js
Fixed index.html, added JS program with example of printing to console
=> #7 1. Created JS program

JoeFoster-cn/index.html, JoeFoster-cn/node.js
Added prompt/alert to node.js and linked to HTML with a script
=> #8 Added prompt/alert

JoeFoster-cn/index.html, JoeFoster-cn/main.css, JoeFoster-cn/node.js
Added GitHub profile and pages links to index.html
=> #9 Added GitHub links to HTML

JoeFoster-cn/index.html
Added footer to index.html and removed ) from index.html
=> #11 Added a footer to HTML

JoeFoster-cn/index.html, JoeFoster-cn/main.css
Updated footer on index.html and styling on main.css
=> #12 Added CSS styling to the footer

SteIddon/README.md
=> Added folder & readme

lrwright/index.html, lrwright/name.js, lrwright/smallApp.js
Ignore the smallApp.js. I accidentally deleted it so had to restore it.
=> 8 Write a small browser js program that uses prompt and alert

SteIddon/index.html
=> #4 Add HTML

lrwright/style.css
=> 12 Create styling for the footer created as part of #12

SteIddon/styles.css
=> #5 Add CSS

NathanRobinson11/prompt.html, NathanRobinson11/prompt.js
prompt.html and prompt.js files adde
=> #8 Prompt and Alert

boothscript/index.html, boothscript/script.js, boothscript/styles.css
Add alerts and prompts. also footer fix #12
=> Boothscript/#12 Alerts and prompts

SteIddon/Promptalert.js, SteIddon/index.html
=> #8 Prompt & Alert

evanmorrisdev/evanmorrisdev.js
=> #7 new file evanmorrisdev.js with Hello World printed to the console.

jadavey91/index.html, jadavey91/task7.js
=> 9 In your index.html page ensure you have links to your github profile and github pages

Connell97/index.html, Connell97/style.css
Added styling and altered the HTML table slightly.
=> 5 Add styling to index.html

ap42m/README.md, ap42m/index.html, ap42m/style.css
added style css and made some minor updates to index.html and reaadme.md
=> #5 added style.ccss

JakeyD11/index.html, JakeyD11/style.css
=> #11 Added nav footer

phiddle/index.html, phiddle/style.css
=> #12 footer

AUTHORS
Had trouble with the initial poul;l request so im re adding my name
=> #1 Added name to authors

README.md
Re added link to read me as the first commit got funny
=> #2 Add Links to read me.md
